Repository boostcampwm-2022/iOS04-Mogakco, pull requests merged in 2022-12, with the labels that each got.

#302 스터디 언어 필터링 조건 수정 (and -> or)
  Mogakco/Sources/Data/Repositories/StudyRepository.swift
  Mogakco/Sources/Presentation/Study/ViewModel/StudyListViewModel.swift
Labels: fix 🔨, 범수

#333 로그인 애니메이션 회전 자연스럽게 수정
  Mogakco/Sources/Presentation/Common/View/AnimationImageView.swift
Labels: fix 🔨, 주훈, SP 3️⃣

#347 앱 아이콘 추가
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  Mogakco/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: chore 🤔, 범수, SP 4️⃣

#373 프로필 편집 화면 로딩 딜레이 오류 개선
  Mogakco/Sources/Presentation/Profile/ViewController/EditProfileViewController.swift
Labels: fix 🔨, 범수, SP 4️⃣

#392 앱 이름 변경 (Mogakco -> 모각코)
  Mogakco/Resources/en.lproj/InfoPlist.strings
  Mogakco/Resources/ko.lproj/InfoPlist.strings
  Mogakco/Resources/ko.lproj/LaunchScreen.strings
Labels: chore 🤔, 범수, SP 4️⃣

#394 앱 세로 모드 고정
  Mogakco/Sources/App/AppDelegate.swift
Labels: chore 🤔, 범수, SP 4️⃣

#412 Controller tap, selected, refresh 이벤트 발생 시 .throttle 오퍼레이터로 중복 방지
  Mogakco/Sources/Presentation/Chat/ViewController/ChatListViewController.swift
  Mogakco/Sources/Presentation/Chat/ViewController/ChatViewController.swift
  Mogakco/Sources/Presentation/Common/ViewController/AlertModalViewController.swift
  Mogakco/Sources/Presentation/Hashtag/ViewController/HashtagSelectViewController.swift
  Mogakco/Sources/Presentation/Login/ViewController/LoginViewController.swift
  Mogakco/Sources/Presentation/Profile/ViewController/EditProfileViewController.swift
  Mogakco/Sources/Presentation/Profile/ViewController/ProfileViewController.swift
  Mogakco/Sources/Presentation/Setting/ViewController/SettingViewController.swift
  Mogakco/Sources/Presentation/Setting/ViewController/WithdrawViewController.swift
  Mogakco/Sources/Presentation/Signup/ViewController/PolicyViewController.swift
  Mogakco/Sources/Presentation/Signup/ViewController/SetEmailViewController.swift
  Mogakco/Sources/Presentation/Signup/ViewController/SetPasswordViewController.swift
  Mogakco/Sources/Presentation/Study/ViewController/CreateStudyViewController.swift
  Mogakco/Sources/Presentation/Study/ViewController/SelectStudySortViewController.swift
  Mogakco/Sources/Presentation/Study/ViewController/StudyDetailViewController.swift
  Mogakco/Sources/Presentation/Study/ViewController/StudyListViewController.swift
Labels: feat 💡, 범수

#431 미모티콘 추가
  Mogakco/Resources/Assets.xcassets/Profile/Contents.json
  Mogakco/Resources/Assets.xcassets/Profile/profile1.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profile/profile1.imageset/profile1.png
  Mogakco/Resources/Assets.xcassets/Profile/profile2.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profile/profile2.imageset/profile2.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile.imageset/profile.jpeg
  Mogakco/Resources/Assets.xcassets/Profiles/profile1.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile1.imageset/profile1.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile10.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile10.imageset/profile10.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile11.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile11.imageset/profile11.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile12.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile12.imageset/profile12.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile13.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile13.imageset/profile13.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile14.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile14.imageset/profile14.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile15.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile15.imageset/profile15.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile16.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile16.imageset/profile16.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile17.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile17.imageset/profile17.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile2.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile2.imageset/profile2.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile3.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile3.imageset/profile3.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile4.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile4.imageset/profile4.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile5.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile5.imageset/profile5.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile6.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile6.imageset/profile6.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile7.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile7.imageset/profile7.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile8.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile8.imageset/profile8.png
  Mogakco/Resources/Assets.xcassets/Profiles/profile9.imageset/Contents.json
  Mogakco/Resources/Assets.xcassets/Profiles/profile9.imageset/profile9.png
  Mogakco/Sources/Presentation/Profile/ViewController/EditProfileViewController.swift
  Mogakco/Sources/Util/Constant/Image.swift
Labels: chore 🤔, 국원, SP 4️⃣

#440 상대 메시지 받을 때 textView 지워지는 버그 해결
  Mogakco/Sources/Presentation/Chat/ViewModel/ChatViewModel.swift
Labels: fix 🔨, 국원

#441 시간 계산 오류
  Mogakco/Sources/Util/Extension/Int+Formatter.swift
Labels: fix 🔨, 국원

#451 모듈 Dependency 오류 수정
  Project.swift
Labels: build ⚙️, 범수, hotfix 🔥
