Repository boostcampwm-2022/iOS04-Mogakco, pull requests merged in 2022-11, with the labels that each got.

#111 스터디 상세 정보 UI
  Mogakco/Mogakco.xcodeproj/project.pbxproj
  Mogakco/Mogakco/Presentation/Common/View/StudyInfoView.swift
  Mogakco/Mogakco/Presentation/StudyDetail/StudyDetailViewController.swift
  Mogakco/Mogakco/Presentation/StudyDetail/View/StudyTitleLabel.swift
  Mogakco/Mogakco/Util/Extension/UIView+AddSubViews.swift
Labels: feat 💡, 주훈, SP 1️⃣

#110 이메일 화면 구현
  Mogakco/Mogakco.xcodeproj/project.pbxproj
  Mogakco/Mogakco/Presentation/Signup/ViewController/SetEmailViewController.swift
Labels: feat 💡, 소민, SP 1️⃣

#107 문자열의 개수를 보여주는 텍스트필드 구현
  Mogakco/Mogakco.xcodeproj/project.pbxproj
  Mogakco/Mogakco/Presentation/Common/View/CountTextField.swift
Labels: feat 💡, 소민, SP 1️⃣

#105 동그란 이미지 프로필 구현
  Mogakco/Mogakco.xcodeproj/project.pbxproj
Labels: feat 💡, 국원, SP 1️⃣

#120 CountTextField 높이 layout 우선 순위 변경
  Mogakco/Sources/Presentation/Common/View/CountTextField.swift
Labels: fix 🔨, 범수

#117 Tuist 도입으로 Firebase 환경 설정 변경
  Mogakco/Resources/GoogleService-Info.plist
Labels: build ⚙️, 범수, SP 1️⃣

#119 RoundProfileImage 입력 인자 변경
  Mogakco/Sources/Presentation/Common/View/RoundProfileImage.swift
Labels: refactor 🏗, 범수

#127 PR 템플릿 이미지 width 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore 🤔, 주훈, SP 1️⃣

#137 프로필, 프로필 생성 / 편집, 채팅 목록 코디네이터 연결
  Mogakco/Sources/Presentation/Chat/ViewController/ChatListViewController.swift
  Mogakco/Sources/Presentation/Chat/ViewModel/ChatListViewModel.swift
  Mogakco/Sources/Presentation/Common/Coordinator/AdditionalSignupCoordinator.swift
  Mogakco/Sources/Presentation/Common/Coordinator/AppCoordinator.swift
  Mogakco/Sources/Presentation/Common/Coordinator/ChatTabCoordinator.swift
  Mogakco/Sources/Presentation/Common/Coordinator/ProfileTabCoordinator.swift
  Mogakco/Sources/Presentation/Common/Coordinator/Protocol/AdditionalSignupCoordinatorProtocol.swift
  Mogakco/Sources/Presentation/Profile/View/ProfileView.swift
  Mogakco/Sources/Presentation/Profile/ViewController/CreateProfileViewController.swift
  Mogakco/Sources/Presentation/Profile/ViewController/ProfileViewController.swift
  Mogakco/Sources/Presentation/Profile/ViewModel/CreateProfiileViewModel.swift
  Mogakco/Sources/Presentation/Profile/ViewModel/ProfileViewModel.swift
Labels: feat 💡, 범수, SP 1️⃣

#138 채팅방 코디네이터 연결
  Mogakco/Sources/Presentation/Chat/ViewController/ChatViewController.swift
  Mogakco/Sources/Presentation/Common/Coordinator/ChatTabCoordinator.swift
Labels: feat 💡, 국원, SP 1️⃣

#159 Moya Custom Network Layer 구현
  Mogakco/Sources/Network/NetworkEventLogger.swift
  Mogakco/Sources/Network/Provider.swift
  Mogakco/Sources/Network/ProviderProtocol.swift
  Mogakco/Sources/Network/TargetType.swift
Labels: feat 💡, 범수, SP 2️⃣

#188 TextView placeholder 레이블 히든 로직 수정
  Mogakco/Sources/Presentation/Common/View/TextView.swift
Labels: fix 🔨, 소민, SP 2️⃣

#204 해시태그 ViewController bind() 메소드 수정
  Mogakco/Sources/Presentation/Hashtag/ViewController/HashtagSelectViewController.swift
Labels: refactor 🏗, 주훈, SP 2️⃣

#213 UIViewController Life Cycle을 RxExtension으로 추가
  Mogakco/Sources/Util/Extension/RxUIViewController+LifeCycle.swift
Labels: feat 💡, 범수

#229 카테고리 2개 선택 이슈 해결
  Mogakco/Sources/Presentation/Hashtag/ViewController/HashtagSelectViewController.swift
Labels: fix 🔨, 주훈, SP 2️⃣

#271 다음(완료) 버튼들의 Y Position이 다른 이슈 해결
  Mogakco/Sources/Presentation/Hashtag/ViewController/HashtagSelectViewController.swift
  Mogakco/Sources/Presentation/Login/ViewController/LoginViewController.swift
  Mogakco/Sources/Presentation/Signup/ViewController/SetEmailViewController.swift
  Mogakco/Sources/Presentation/Signup/ViewController/SetPasswordViewController.swift
  Mogakco/Sources/Presentation/Study/ViewController/StudyDetailViewController.swift
  Mogakco/Sources/Util/Constant/Layout.swift
Labels: fix 🔨, 주훈, SP 3️⃣

#276 rebase 때 잘못 수정된 코드 제거
  Mogakco/Sources/Data/Repositories/StudyRepository.swift
  Mogakco/Sources/Domain/Repositories/StudyRepositoryProtocol.swift
Labels: fix 🔨, 국원

#261 채팅방 목록 호출 시 유저 정보 호출 기능 구현
  Mogakco/Sources/Data/DataMapping/ChatRoomResponseDTO.swift
  Mogakco/Sources/Data/Repositories/ChatRoomRepository.swift
  Mogakco/Sources/Domain/Entities/ChatRoom.swift
  Mogakco/Sources/Domain/UseCases/ChatRoomListUseCase.swift
Labels: feat 💡, 범수, SP 3️⃣

#275 스터디 목록 새로고침(위로 당길때)
  Mogakco/Sources/Presentation/Study/ViewController/StudyListViewController.swift
  Mogakco/Sources/Presentation/Study/ViewModel/StudyListViewModel.swift
Labels: feat 💡, 주훈, SP 3️⃣
